Github Actions: Add Phpstan
Icinga/ipl-validator pull request #30
Opened 2023-06-19 14:36 UTC by sukhwinder33445

2023-08-23 12:56 UTC, nilmerg requested changes

2023-08-23 12:56 UTC, nilmerg commented on src/BetweenValidator.php
> +    /** @var scalar Min value */
int|float please, scalar is not native

2023-08-23 14:18 UTC, sukhwinder33445 commented on src/ValidatorChain.php
> +         */
`PriorityQueue` is from `ipl\Stdlib`.

2023-08-24 06:58 UTC, nilmerg approved these changes

2023-08-24 07:01 UTC, merged