Add HexColorValidator
Icinga/ipl-validator pull request #9
Opened 2022-09-19 10:01 UTC by Al2Klimov

2022-10-21 12:18 UTC, lippserd requested changes

2022-10-21 12:18 UTC, lippserd commented on src/HexColorValidator.php
> +        if (! is_string($value)) {
This is not a validation but a programming error and since `preg_match` already expects a string, you can remove this.

2022-10-21 12:18 UTC, lippserd commented on src/HexColorValidator.php
> +                $this->translate("Color string not in the expected format: %s"),
Remove the colon and use `#rrggbb' for the format.

2022-10-21 12:18 UTC, lippserd commented on tests/HexColorValidatorTest.php
> +        $this->assertFalse($validator->isValid(false), 'false is not a valid color');
Remove that one as we are expecting strings only.

2022-10-21 12:18 UTC, lippserd commented on tests/HexColorValidatorTest.php
> +    public function testColorValidatorWithInvalidColors(): void
Also test `ffffff` without `#` please.

2022-10-21 13:05 UTC, lippserd requested changes

2022-10-21 13:05 UTC, lippserd commented on tests/HexColorValidatorTest.php
> +        $this->assertFalse($validator->isValid('ffffff'), '09afAF is not a valid color');
🐘 oversight 😉

2022-10-21 13:58 UTC, Al2Klimov commented on tests/HexColorValidatorTest.php
> +        $this->assertFalse($validator->isValid('ffffff'), '09afAF is not a valid color');
Ah, my favourite animal! 🤗

2022-10-28 10:38 UTC, lippserd requested changes

2022-10-28 10:38 UTC, lippserd commented on src/HexColorValidator.php
> +                $this->translate("Color string not in the expected format %s"),
Please use single quotes.

2022-10-28 10:38 UTC, lippserd commented on tests/HexColorValidatorTest.php
> +        $this->assertTrue((new HexColorValidator())->isValid('#09afAF'), '#09afAF is a valid color');
Please add a newline before.

2022-10-28 12:26 UTC, lippserd approved these changes

2022-10-28 12:26 UTC, merged